### PR TITLE
Add prior exact/approx comparison

### PR DESCRIPTION
**Pull request by zietzm**

### CODE REVIEW

**Comment by dhimmel** [comment]
Interesting to compare to plot at https://think-lab.github.io/d/201/#2. Possibly worth logit transform. Also possibly worth plotting scaled degree-prod versus edge prior

**Comment by zietzm** [comment]
Here's an example with scaled degree.

image

And here's the logit

image

**Comment by dhimmel** [comment]
> Here's an example with scaled degree.

Ah yes, that is ugly and shows how bad scaled degree is. Nice to have here but for manuscript probably best to just have analytical approx

**Comment by zietzm** [comment]
With logit:
image

Without logit:
image

**Pull request merged**
